server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/environment_db?stringtype=unspecified
    username: env_app_user
    password: "2112" # KIEM TRA LAI PASSWORD NAY TREN MAY BAN
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
          facebook:
            client-id: "YOUR_FACEBOOK_APP_ID"
            client-secret: "YOUR_FACEBOOK_APP_SECRET"

facebook:
  api:
    user-info-uri: "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"

jwt:
  secret:
    key: MjAxNS0xMDExY2h1eWVuZGVtb2JpbGUxMGRpZW0xMjM0NQ== 
  expiration:
    ms: 86400000

aqi:
  api:
    key: 5ad9ae819b67abf939f3e0d4604bd362
    base-url: https://api.openweathermap.org/data/2.5/air_pollution
    geocoding-url: https://api.openweathermap.org/geo/1.0/reverse